### PR TITLE
Added search bar

### PR DESCRIPTION
**Pull request by Ramon-W**
Users can now search up classes by both their title and their courseId.
Added better error handling for edge cases. 
Neatly aligned the form with uniform spacing.

### CODE REVIEW

**Comment by Ramon-W** [comment]
Screen Shot 2023-03-06 at 7 35 09 PM
-4807fef477de.png">

**Comment by WinbertZhang** [comment]
Hey @Ramon-W it looks like your current solution is making an API call and including the user's text as the courseId. It doesn't seem to work since the UCSB API doesn't actually allow us to search by course name. None of the parameters they provide are exactly what we want since we want the users to be able to type in something along the lines of "cmpsc 24" or "pstat 120a" and find the class. One solution we can try is to store the names of all the classes into a database and query the search from there.

**Comment by Ramon-W** [comment]
Hi Winbert. I believe you are proxying the local frontend requests to the deployed web app, which does not have the updated backend. In vue.config.js you need to uncomment line 2 and comment line 1.

**Comment by WinbertZhang** [comment]
> Hi Winbert. I believe you are proxying the local frontend requests to the deployed web app, which does not have the updated backend. In vue.config.js you need to uncomment line 2 and comment line 1.

Hey Ramon. Sorry about that looks like the feature works now with the updated backend. I did wonder if we could add some sort of check to see if the text the user types is one of the departments, like pstat or cmpsc, and have the classes under that department load as well - similar to this page: https://gogaucho.app/#/course. We don't have to add this right away but it's another feature that we could work on, what do you think?

**Review by WinbertZhang — APPROVED** [review]
Great job on the search bar!

**Pull request merged**
