### PR TITLE
Added logout button

### PR DESCRIPTION
**Pull request by Ponmo**
Screen Shot 2023-01-27 at 4 52 38 PM

Will show a log-out button when the user is logged in.

### CODE REVIEW

**Comment by WinbertZhang** [comment]
After logging in, seems like sign-in button still exists:
Screenshot 2023-01-30 at 12 49 46 PM

**Comment by Ponmo** [comment]
Hey Winbert,

Are you using localhost:8080 to log in and log out? That might be the problem

**Comment by WinbertZhang** [comment]
> Hey Winbert,
> 
> Are you using localhost:8088 to log in and log out? That might be the problem

Ah I see, using localhost:8088 to sign in works but what does the logout process look like?

**Comment by Ponmo** [comment]
Hey Winbert, just fixed it so that you can see the logout button on the backend once you log in. It should be in the navbar.

**Review by WinbertZhang — APPROVED** [review]
Logout button looks good, merging to main

**Pull request merged**
