### PR TITLE
Resolved crunchtime issue #9

### PR DESCRIPTION
**Pull request by MStriker11**

### CODE REVIEW

**Review by WinbertZhang — CHANGES_REQUESTED** [review]
Looks like moving the groupTimes map caused when compiling, please try to look into a way around this issue.

**Comment by Ramon-W** [comment]
Note that since migrating to MongoDB, files involving data were heavily changed (SQL annotations like @ElementCollection were removed). You can try to see if merging main into your branch works.

**Comment by MStriker11** [comment]
The SQL annotation was not the issue; a new pointer reference to the map is necessary while clearing a preexisting map returns an error. Not sure why that is though.

**Review by WinbertZhang — APPROVED** [review]
Looks good now, thanks for working on this Olivia!

**Pull request merged**
